platform: linux

image_resource:
  type: docker-image
  source:
    repository: cnsadmin/struts-example
    tag: latest
inputs:
- name: struts-examples
- name: struts-app-build-artifacts
run:
  path: struts-examples/ci/tasks/struts-app/cf-push/task.sh
params:
  CF_API: ((CF_API))
  CF_API_USER: ((CF_API_USER))
  CF_API_PASSWORD: ((CF_API_PASSWORD))
  AWS_ACCESS_KEY: ((AWS_ACCESS_KEY))
  AWS_SECRET_KEY: ((AWS_SECRET_KEY))
  AWS_REGION_NAME: ((AWS_REGION_NAME))
  S3_ENDPOINT: ((S3_ENDPOINT))
  S3_BUCKET: ((S3_BUCKET))
