platform: linux

image_resource:
  type: docker-image
  source:
    repository: cnsadmin/struts-example
    tag: latest
inputs:
- name: struts-examples
run:
  path: struts-examples/ci/tasks/struts-app/compile/task.sh
