platform: linux

image_resource:
  type: docker-image
  source:
    repository: cnsadmin/vw-maven
    tag: latest
inputs:
- name: struts-examples
run:
  path: struts-examples/ci/struts-app/tasks/compile/task.sh
