platform: linux

image_resource:
  type: docker-image
  source:
    repository: cnsadmin/struts-example
    tag: latest
inputs:
- name: struts-examples
outputs:
- name: build_artifacts
run:
  path: struts-examples/ci/tasks/struts-app/compile/task.sh
params:
  AWS_ACCESS_KEY: ((AWS_ACCESS_KEY))
  AWS_SECRET_KEY: ((AWS_SECRET_KEY))
  AWS_REGION_NAME: ((AWS_REGION_NAME))
  S3_ENDPOINT: ((S3_ENDPOINT))
  S3_BUCKET: ((S3_BUCKET))